### ISSUE TITLE
Pod and Service labels consistency

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry/cf-k8s-networking#22]
It'll be nice to have the same labels for pods and services to able to reuse the selector find services and pods corresponding to an app GUID. Right now pods have `cloudfoundry.org/app_guid` and `cloudfoundry.org/guid` labels and services have `cloudfoundry.org/app`. 

AFAIK, having the same label is a good practice in Kubernetes which eases operators' experience and leverages tools working Kubernetes cluster to group objects under the same entity. https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

**Comment by mike1808** [comment]
I'm currently working on it.

**Comment by cppforlife** [comment]
i would recommend using `app-guid` instead of `app_guid`.

**Comment by mike1808** [comment]
@cppforlife is that a best practice in k8s? I don't what's the naming guidelines in this ecosystem
