### ISSUE TITLE
Do you have examples of how I can deploy this with Eirini?

### ISSUE THREAD

**Issue by mike1808** [cloudfoundry/cf-k8s-networking#29]
Hi. The README says I have to have Eirini based deployment but I cannot find any documentation on how to set up it. I heard about [cf-for-k8s](https://github.com/cloudfoundry/cf-for-k8s) project which consumes this repo. Maybe we can include it in the README?

**Comment by ndhanushkodi** [comment]
The [cf-for-k8s](https://github.com/cloudfoundry/cf-for-k8s) repo now has deployment instructions. We have written a [story](https://www.pivotaltracker.com/story/show/173044078) to update our main readme to not have independent deployment instructions. Closing this issue now!
