### ISSUE TITLE
request to pin `cfroutesync` image

### ISSUE THREAD

**Issue by jamespollard8** [cloudfoundry/cf-k8s-networking#36]
We're currently overriding your default with `"gcr.io/cf-networking-images/cf-k8s-networking/cfroutesync@sha256:758abd1b6144596cef74ad4805bc7e1a6055142cab5719f0d42d0321a14a190d"` but we'd prefer that y'all dictate the preferred image SHA, if that seems desirable to you.

The current line of code pointing to "latest" is here: https://github.com/cloudfoundry/cf-k8s-networking/blob/master/config/cfroutesync/values.yaml#L10

Best,
relint

**Comment by kauana** [comment]
This issue was fixed by this [PR](https://github.com/cloudfoundry/cf-for-k8s/pull/128).

**Comment by XanderStrike** [comment]
We now have a CI task that will keep that image sha up to date. I think it's okay for you to remove your override now.

**Comment by jamespollard8** [comment]
Oh cool, looks like we first need to get cf-k8s-networking updated in cf-for-k8s. I think it'd make sense to remove our override as part of that PR.

Do y'all have plans to bump networking in cf-for-k8s anytime soon? If you have a story or want to kick that off, it might be a good idea to add a task/reminder to remove our override here: https://github.com/cloudfoundry/cf-for-k8s/blob/master/config/values.yml#L30
